version: "3.7"

volumes:
        postres_data: 
                


services:       
        postgres:
                image: postgres:11-alpine
                
                ports:
                        - ${EJEMPLO_PGPORT:-5432}:5432
                volumes:
                        - postgres_data:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: copsis